import { OrganizationNode } from '../types/organization';
import { KPI } from '../types/kpis';

/**
 * Maps organizational unit IDs to their KPI data
 * In a real application, this would come from a database or API
 */
export const orgKpiData: Record<string, KPI[]> = {
  // Company level (aggregated from all divisions)
  'amdocs': [],
  
  // Technology Division
  'division-1': [],
  
  // Software Development Unit
  'unit-1-1': [],
  
  // AI Engineering Department
  'dept-1-1-1': [],
  
  // ML Platform Team
  'team-1-1-1-1': [
    {
      id: 'adoption-percentage',
      name: 'Adoption Percentage',
      description: 'Overall AI adoption rate',
      currentValue: 75.0,
      targetValue: 90.0,
      scale: { min: 1, max: 100, unit: '%' },
      trend: 'up',
      category: 'Adoption',
      history: [
        { date: '2024-10-14', value: 65.0 },
        { date: '2024-11-14', value: 70.0 },
        { date: '2024-12-14', value: 72.5 },
        { date: '2025-01-06', value: 75.0 }
      ],
      subMetrics: [
        {
          id: 'active-users',
          name: 'Active Users',
          description: 'Percentage of active users out of total users',
          currentValue: 380,
          targetValue: 550,
          scale: { min: 0, max: 1000, unit: 'users' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 320 },
            { date: '2024-11-14', value: 340 },
            { date: '2024-12-14', value: 365 },
            { date: '2025-01-06', value: 380 }
          ]
        },
        {
          id: 'committed-lines-percentage',
          name: 'Committed Lines of Code',
          description: 'Percentage of committed lines of code generated by AI out of total',
          currentValue: 50.0,
          targetValue: 75.0,
          scale: { min: 0, max: 100, unit: '%' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 40.0 },
            { date: '2024-11-14', value: 45.0 },
            { date: '2024-12-14', value: 48.0 },
            { date: '2025-01-06', value: 50.0 }
          ]
        }
      ]
    },
    {
      id: 'roi',
      name: 'Velocity and Quality',
      description: 'Velocity and Quality metrics',
      currentValue: 3.5,
      targetValue: 5.0,
      scale: { min: 0, max: 10, unit: 'x' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 3.0 },
        { date: '2024-11-14', value: 3.2 },
        { date: '2024-12-14', value: 3.4 },
        { date: '2025-01-06', value: 3.5 }
      ],
      subMetrics: [
        {
          id: 'cycle-time',
          name: 'Cycle Time',
          description: 'Average development cycle time',
          currentValue: 11.0,
          targetValue: 7.0,
          scale: { min: 0, max: 30, unit: 'days' },
          trend: 'down',
          history: [
            { date: '2024-10-14', value: 14.0 },
            { date: '2024-11-14', value: 13.0 },
            { date: '2024-12-14', value: 12.0 },
            { date: '2025-01-06', value: 11.0 }
          ]
        },
        {
          id: 'quality-index',
          name: 'Quality Index',
          description: 'Overall quality score for AI-generated outputs',
          currentValue: 82.0,
          targetValue: 92.0,
          scale: { min: 1, max: 100, unit: '%' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 76.0 },
            { date: '2024-11-14', value: 78.0 },
            { date: '2024-12-14', value: 80.0 },
            { date: '2025-01-06', value: 82.0 }
          ]
        }
      ]
    },
    {
      id: 'cost',
      name: 'Financial Index',
      description: 'Financial cost metrics',
      currentValue: 72.0,
      targetValue: 85.0,
      scale: { min: 0, max: 100, unit: '%' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 68.0 },
        { date: '2024-11-14', value: 70.0 },
        { date: '2024-12-14', value: 71.0 },
        { date: '2025-01-06', value: 72.0 }
      ],
      subMetrics: [
        {
          id: 'estimation-trend',
          name: 'Estimation Trend',
          description: 'Trend in cost estimation accuracy',
          currentValue: 78.0,
          targetValue: 92.0,
          scale: { min: 0, max: 100, unit: '%' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 72.0 },
            { date: '2024-11-14', value: 74.0 },
            { date: '2024-12-14', value: 76.0 },
            { date: '2025-01-06', value: 78.0 }
          ]
        },
        {
          id: 'revenue-per-employee',
          name: 'Overall Revenue per Employee',
          description: 'Total revenue generated per employee',
          currentValue: 135000,
          targetValue: 160000,
          scale: { min: 0, max: 200000, unit: '$' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 125000 },
            { date: '2024-11-14', value: 128000 },
            { date: '2024-12-14', value: 132000 },
            { date: '2025-01-06', value: 135000 }
          ]
        }
      ]
    },
    {
      id: 'dev-experience',
      name: 'Dev Experience',
      description: 'Developer experience score for AI tools and workflows',
      currentValue: 3.6,
      targetValue: 5.0,
      scale: { min: 1, max: 5, unit: 'score' },
      trend: 'up',
      category: 'Quality',
      history: [
        { date: '2024-10-14', value: 3.2 },
        { date: '2024-11-14', value: 3.4 },
        { date: '2024-12-14', value: 3.5 },
        { date: '2025-01-06', value: 3.6 }
      ]
    }
  ],
  
  // AI Tools Team
  'team-1-1-1-2': [
    {
      id: 'adoption-percentage',
      name: 'Adoption Percentage',
      description: 'Overall AI adoption rate',
      currentValue: 70.0,
      targetValue: 85.0,
      scale: { min: 1, max: 100, unit: '%' },
      trend: 'up',
      category: 'Adoption',
      history: [
        { date: '2024-10-14', value: 60.0 },
        { date: '2024-11-14', value: 65.0 },
        { date: '2024-12-14', value: 68.0 },
        { date: '2025-01-06', value: 70.0 }
      ],
      subMetrics: [
        {
          id: 'active-users',
          name: 'Active Users',
          description: 'Percentage of active users out of total users',
          currentValue: 350,
          targetValue: 520,
          scale: { min: 0, max: 1000, unit: 'users' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 290 },
            { date: '2024-11-14', value: 310 },
            { date: '2024-12-14', value: 335 },
            { date: '2025-01-06', value: 350 }
          ]
        },
        {
          id: 'committed-lines-percentage',
          name: 'Committed Lines of Code',
          description: 'Percentage of committed lines of code generated by AI out of total',
          currentValue: 47.0,
          targetValue: 72.0,
          scale: { min: 0, max: 100, unit: '%' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 37.0 },
            { date: '2024-11-14', value: 42.0 },
            { date: '2024-12-14', value: 45.0 },
            { date: '2025-01-06', value: 47.0 }
          ]
        }
      ]
    },
    {
      id: 'roi',
      name: 'Velocity and Quality',
      description: 'Velocity and Quality metrics',
      currentValue: 3.2,
      targetValue: 5.0,
      scale: { min: 0, max: 10, unit: 'x' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 2.8 },
        { date: '2024-11-14', value: 3.0 },
        { date: '2024-12-14', value: 3.1 },
        { date: '2025-01-06', value: 3.2 }
      ],
      subMetrics: [
        {
          id: 'cycle-time',
          name: 'Cycle Time',
          description: 'Average development cycle time',
          currentValue: 12.8,
          targetValue: 8.5,
          scale: { min: 0, max: 30, unit: 'days' },
          trend: 'down',
          history: [
            { date: '2024-10-14', value: 15.5 },
            { date: '2024-11-14', value: 14.5 },
            { date: '2024-12-14', value: 13.5 },
            { date: '2025-01-06', value: 12.8 }
          ]
        },
        {
          id: 'quality-index',
          name: 'Quality Index',
          description: 'Overall quality score for AI-generated outputs',
          currentValue: 79.0,
          targetValue: 91.0,
          scale: { min: 1, max: 100, unit: '%' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 73.0 },
            { date: '2024-11-14', value: 75.0 },
            { date: '2024-12-14', value: 77.0 },
            { date: '2025-01-06', value: 79.0 }
          ]
        }
      ]
    },
    {
      id: 'cost',
      name: 'Financial Index',
      description: 'Financial cost metrics',
      currentValue: 68.0,
      targetValue: 82.0,
      scale: { min: 0, max: 100, unit: '%' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 64.0 },
        { date: '2024-11-14', value: 66.0 },
        { date: '2024-12-14', value: 67.0 },
        { date: '2025-01-06', value: 68.0 }
      ],
      subMetrics: [
        {
          id: 'estimation-trend',
          name: 'Estimation Trend',
          description: 'Trend in cost estimation accuracy',
          currentValue: 73.0,
          targetValue: 88.0,
          scale: { min: 0, max: 100, unit: '%' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 67.0 },
            { date: '2024-11-14', value: 69.0 },
            { date: '2024-12-14', value: 71.0 },
            { date: '2025-01-06', value: 73.0 }
          ]
        },
        {
          id: 'revenue-per-employee',
          name: 'Overall Revenue per Employee',
          description: 'Total revenue generated per employee',
          currentValue: 128000,
          targetValue: 155000,
          scale: { min: 0, max: 200000, unit: '$' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 118000 },
            { date: '2024-11-14', value: 121000 },
            { date: '2024-12-14', value: 125000 },
            { date: '2025-01-06', value: 128000 }
          ]
        }
      ]
    },
    {
      id: 'dev-experience',
      name: 'Dev Experience',
      description: 'Developer experience score for AI tools and workflows',
      currentValue: 3.4,
      targetValue: 5.0,
      scale: { min: 1, max: 5, unit: 'score' },
      trend: 'up',
      category: 'Quality',
      history: [
        { date: '2024-10-14', value: 3.0 },
        { date: '2024-11-14', value: 3.2 },
        { date: '2024-12-14', value: 3.3 },
        { date: '2025-01-06', value: 3.4 }
      ]
    }
  ],
  
  // DevOps Department
  'dept-1-1-2': [],
  
  // Infrastructure Team
  'team-1-1-2-1': [
    {
      id: 'adoption-percentage',
      name: 'Adoption Percentage',
      description: 'Overall AI adoption rate',
      currentValue: 65.0,
      targetValue: 80.0,
      scale: { min: 1, max: 100, unit: '%' },
      trend: 'up',
      category: 'Adoption',
      history: [
        { date: '2024-10-14', value: 55.0 },
        { date: '2024-11-14', value: 60.0 },
        { date: '2024-12-14', value: 63.0 },
        { date: '2025-01-06', value: 65.0 }
      ],
      subMetrics: [
        {
          id: 'active-users',
          name: 'Active Users',
          description: 'Percentage of active users out of total users',
          currentValue: 320,
          targetValue: 480,
          scale: { min: 0, max: 1000, unit: 'users' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 260 },
            { date: '2024-11-14', value: 285 },
            { date: '2024-12-14', value: 305 },
            { date: '2025-01-06', value: 320 }
          ]
        },
        {
          id: 'committed-lines-percentage',
          name: 'Committed Lines of Code',
          description: 'Percentage of committed lines of code generated by AI out of total',
          currentValue: 42.0,
          targetValue: 68.0,
          scale: { min: 0, max: 100, unit: '%' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 32.0 },
            { date: '2024-11-14', value: 37.0 },
            { date: '2024-12-14', value: 40.0 },
            { date: '2025-01-06', value: 42.0 }
          ]
        }
      ]
    },
    {
      id: 'roi',
      name: 'Velocity and Quality',
      description: 'Velocity and Quality metrics',
      currentValue: 2.8,
      targetValue: 4.5,
      scale: { min: 0, max: 10, unit: 'x' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 2.5 },
        { date: '2024-11-14', value: 2.6 },
        { date: '2024-12-14', value: 2.7 },
        { date: '2025-01-06', value: 2.8 }
      ],
      subMetrics: [
        {
          id: 'cycle-time',
          name: 'Cycle Time',
          description: 'Average development cycle time',
          currentValue: 13.5,
          targetValue: 9.0,
          scale: { min: 0, max: 30, unit: 'days' },
          trend: 'down',
          history: [
            { date: '2024-10-14', value: 16.5 },
            { date: '2024-11-14', value: 15.5 },
            { date: '2024-12-14', value: 14.5 },
            { date: '2025-01-06', value: 13.5 }
          ]
        },
        {
          id: 'quality-index',
          name: 'Quality Index',
          description: 'Overall quality score for AI-generated outputs',
          currentValue: 76.0,
          targetValue: 88.0,
          scale: { min: 1, max: 100, unit: '%' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 70.0 },
            { date: '2024-11-14', value: 72.0 },
            { date: '2024-12-14', value: 74.0 },
            { date: '2025-01-06', value: 76.0 }
          ]
        }
      ]
    },
    {
      id: 'cost',
      name: 'Financial Index',
      description: 'Financial cost metrics',
      currentValue: 66.0,
      targetValue: 80.0,
      scale: { min: 0, max: 100, unit: '%' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 62.0 },
        { date: '2024-11-14', value: 64.0 },
        { date: '2024-12-14', value: 65.0 },
        { date: '2025-01-06', value: 66.0 }
      ],
      subMetrics: [
        {
          id: 'estimation-trend',
          name: 'Estimation Trend',
          description: 'Trend in cost estimation accuracy',
          currentValue: 70.0,
          targetValue: 85.0,
          scale: { min: 0, max: 100, unit: '%' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 64.0 },
            { date: '2024-11-14', value: 66.0 },
            { date: '2024-12-14', value: 68.0 },
            { date: '2025-01-06', value: 70.0 }
          ]
        },
        {
          id: 'revenue-per-employee',
          name: 'Overall Revenue per Employee',
          description: 'Total revenue generated per employee',
          currentValue: 120000,
          targetValue: 145000,
          scale: { min: 0, max: 200000, unit: '$' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 110000 },
            { date: '2024-11-14', value: 113000 },
            { date: '2024-12-14', value: 117000 },
            { date: '2025-01-06', value: 120000 }
          ]
        }
      ]
    },
    {
      id: 'dev-experience',
      name: 'Dev Experience',
      description: 'Developer experience score for AI tools and workflows',
      currentValue: 3.0,
      targetValue: 4.8,
      scale: { min: 1, max: 5, unit: 'score' },
      trend: 'up',
      category: 'Quality',
      history: [
        { date: '2024-10-14', value: 2.6 },
        { date: '2024-11-14', value: 2.8 },
        { date: '2024-12-14', value: 2.9 },
        { date: '2025-01-06', value: 3.0 }
      ]
    }
  ],
  
  // Product Management Unit
  'unit-1-2': [],
  
  // Product Strategy Department
  'dept-1-2-1': [
    {
      id: 'adoption-percentage',
      name: 'Adoption Percentage',
      description: 'Overall AI adoption rate',
      currentValue: 60.0,
      targetValue: 75.0,
      scale: { min: 1, max: 100, unit: '%' },
      trend: 'up',
      category: 'Adoption',
      history: [
        { date: '2024-10-14', value: 50.0 },
        { date: '2024-11-14', value: 55.0 },
        { date: '2024-12-14', value: 58.0 },
        { date: '2025-01-06', value: 60.0 }
      ],
      subMetrics: [
        {
          id: 'active-users',
          name: 'Active Users',
          description: 'Percentage of active users out of total users',
          currentValue: 300,
          targetValue: 450,
          scale: { min: 0, max: 1000, unit: 'users' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 250 },
            { date: '2024-11-14', value: 270 },
            { date: '2024-12-14', value: 290 },
            { date: '2025-01-06', value: 300 }
          ]
        },
        {
          id: 'committed-lines-percentage',
          name: 'Committed Lines of Code',
          description: 'Percentage of committed lines of code generated by AI out of total',
          currentValue: 40.0,
          targetValue: 65.0,
          scale: { min: 0, max: 100, unit: '%' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 30.0 },
            { date: '2024-11-14', value: 35.0 },
            { date: '2024-12-14', value: 38.0 },
            { date: '2025-01-06', value: 40.0 }
          ]
        }
      ]
    },
    {
      id: 'roi',
      name: 'Velocity and Quality',
      description: 'Velocity and Quality metrics',
      currentValue: 2.5,
      targetValue: 4.0,
      scale: { min: 0, max: 10, unit: 'x' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 2.2 },
        { date: '2024-11-14', value: 2.3 },
        { date: '2024-12-14', value: 2.4 },
        { date: '2025-01-06', value: 2.5 }
      ],
      subMetrics: [
        {
          id: 'cycle-time',
          name: 'Cycle Time',
          description: 'Average development cycle time',
          currentValue: 14.5,
          targetValue: 10.0,
          scale: { min: 0, max: 30, unit: 'days' },
          trend: 'down',
          history: [
            { date: '2024-10-14', value: 17.0 },
            { date: '2024-11-14', value: 16.0 },
            { date: '2024-12-14', value: 15.5 },
            { date: '2025-01-06', value: 14.5 }
          ]
        },
        {
          id: 'quality-index',
          name: 'Quality Index',
          description: 'Overall quality score for AI-generated outputs',
          currentValue: 73.0,
          targetValue: 86.0,
          scale: { min: 1, max: 100, unit: '%' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 68.0 },
            { date: '2024-11-14', value: 70.0 },
            { date: '2024-12-14', value: 72.0 },
            { date: '2025-01-06', value: 73.0 }
          ]
        }
      ]
    },
    {
      id: 'cost',
      name: 'Financial Index',
      description: 'Financial cost metrics',
      currentValue: 64.0,
      targetValue: 78.0,
      scale: { min: 0, max: 100, unit: '%' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 60.0 },
        { date: '2024-11-14', value: 62.0 },
        { date: '2024-12-14', value: 63.0 },
        { date: '2025-01-06', value: 64.0 }
      ],
      subMetrics: [
        {
          id: 'estimation-trend',
          name: 'Estimation Trend',
          description: 'Trend in cost estimation accuracy',
          currentValue: 68.0,
          targetValue: 83.0,
          scale: { min: 0, max: 100, unit: '%' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 62.0 },
            { date: '2024-11-14', value: 64.0 },
            { date: '2024-12-14', value: 66.0 },
            { date: '2025-01-06', value: 68.0 }
          ]
        },
        {
          id: 'revenue-per-employee',
          name: 'Overall Revenue per Employee',
          description: 'Total revenue generated per employee',
          currentValue: 115000,
          targetValue: 140000,
          scale: { min: 0, max: 200000, unit: '$' },
          trend: 'up',
          history: [
            { date: '2024-10-14', value: 105000 },
            { date: '2024-11-14', value: 108000 },
            { date: '2024-12-14', value: 112000 },
            { date: '2025-01-06', value: 115000 }
          ]
        }
      ]
    },
    {
      id: 'dev-experience',
      name: 'Dev Experience',
      description: 'Developer experience score for AI tools and workflows',
      currentValue: 2.8,
      targetValue: 4.5,
      scale: { min: 1, max: 5, unit: 'score' },
      trend: 'up',
      category: 'Quality',
      history: [
        { date: '2024-10-14', value: 2.4 },
        { date: '2024-11-14', value: 2.6 },
        { date: '2024-12-14', value: 2.7 },
        { date: '2025-01-06', value: 2.8 }
      ]
    }
  ],
  
  // Business Division
  'division-2': [],
  
  // Sales Unit
  'unit-2-1': [],
  
  // Enterprise Sales Department
  'dept-2-1-1': [],
  
  // North America Sales Team
  'team-2-1-1-1': [
    {
      id: 'adoption-percentage',
      name: 'Adoption Percentage',
      description: 'Overall AI adoption rate',
      currentValue: 55.0,
      targetValue: 70.0,
      scale: { min: 1, max: 100, unit: '%' },
      trend: 'up',
      category: 'Adoption',
      history: [
        { date: '2024-10-14', value: 45.0 },
        { date: '2024-11-14', value: 50.0 },
        { date: '2024-12-14', value: 53.0 },
        { date: '2025-01-06', value: 55.0 }
      ]
    },
    {
      id: 'roi',
      name: 'Velocity and Quality',
      description: 'Velocity and Quality metrics',
      currentValue: 2.2,
      targetValue: 3.5,
      scale: { min: 0, max: 10, unit: 'x' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 2.0 },
        { date: '2024-11-14', value: 2.1 },
        { date: '2024-12-14', value: 2.15 },
        { date: '2025-01-06', value: 2.2 }
      ]
    },
    {
      id: 'cost',
      name: 'Financial Index',
      description: 'Financial cost metrics',
      currentValue: 62.0,
      targetValue: 75.0,
      scale: { min: 0, max: 100, unit: '%' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 58.0 },
        { date: '2024-11-14', value: 60.0 },
        { date: '2024-12-14', value: 61.0 },
        { date: '2025-01-06', value: 62.0 }
      ]
    }
  ],
  
  // EMEA Sales Team
  'team-2-1-1-2': [
    {
      id: 'adoption-percentage',
      name: 'Adoption Percentage',
      description: 'Overall AI adoption rate',
      currentValue: 50.0,
      targetValue: 65.0,
      scale: { min: 1, max: 100, unit: '%' },
      trend: 'up',
      category: 'Adoption',
      history: [
        { date: '2024-10-14', value: 40.0 },
        { date: '2024-11-14', value: 45.0 },
        { date: '2024-12-14', value: 48.0 },
        { date: '2025-01-06', value: 50.0 }
      ]
    },
    {
      id: 'roi',
      name: 'Velocity and Quality',
      description: 'Velocity and Quality metrics',
      currentValue: 2.0,
      targetValue: 3.2,
      scale: { min: 0, max: 10, unit: 'x' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 1.8 },
        { date: '2024-11-14', value: 1.9 },
        { date: '2024-12-14', value: 1.95 },
        { date: '2025-01-06', value: 2.0 }
      ]
    },
    {
      id: 'cost',
      name: 'Financial Index',
      description: 'Financial cost metrics',
      currentValue: 60.0,
      targetValue: 72.0,
      scale: { min: 0, max: 100, unit: '%' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 56.0 },
        { date: '2024-11-14', value: 58.0 },
        { date: '2024-12-14', value: 59.0 },
        { date: '2025-01-06', value: 60.0 }
      ]
    }
  ],
  
  // Customer Success Unit
  'unit-2-2': [],
  
  // Support Department
  'dept-2-2-1': [
    {
      id: 'adoption-percentage',
      name: 'Adoption Percentage',
      description: 'Overall AI adoption rate',
      currentValue: 45.0,
      targetValue: 60.0,
      scale: { min: 1, max: 100, unit: '%' },
      trend: 'up',
      category: 'Adoption',
      history: [
        { date: '2024-10-14', value: 35.0 },
        { date: '2024-11-14', value: 40.0 },
        { date: '2024-12-14', value: 43.0 },
        { date: '2025-01-06', value: 45.0 }
      ]
    },
    {
      id: 'roi',
      name: 'Velocity and Quality',
      description: 'Velocity and Quality metrics',
      currentValue: 1.8,
      targetValue: 3.0,
      scale: { min: 0, max: 10, unit: 'x' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 1.5 },
        { date: '2024-11-14', value: 1.6 },
        { date: '2024-12-14', value: 1.7 },
        { date: '2025-01-06', value: 1.8 }
      ]
    },
    {
      id: 'cost',
      name: 'Financial Index',
      description: 'Financial cost metrics',
      currentValue: 58.0,
      targetValue: 70.0,
      scale: { min: 0, max: 100, unit: '%' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 54.0 },
        { date: '2024-11-14', value: 56.0 },
        { date: '2024-12-14', value: 57.0 },
        { date: '2025-01-06', value: 58.0 }
      ]
    }
  ],
  
  // Operations Division
  'division-3': [],
  
  // HR Unit
  'unit-3-1': [],
  
  // Talent Acquisition Department
  'dept-3-1-1': [
    {
      id: 'adoption-percentage',
      name: 'Adoption Percentage',
      description: 'Overall AI adoption rate',
      currentValue: 40.0,
      targetValue: 55.0,
      scale: { min: 1, max: 100, unit: '%' },
      trend: 'up',
      category: 'Adoption',
      history: [
        { date: '2024-10-14', value: 30.0 },
        { date: '2024-11-14', value: 35.0 },
        { date: '2024-12-14', value: 38.0 },
        { date: '2025-01-06', value: 40.0 }
      ]
    },
    {
      id: 'roi',
      name: 'Velocity and Quality',
      description: 'Velocity and Quality metrics',
      currentValue: 1.5,
      targetValue: 2.8,
      scale: { min: 0, max: 10, unit: 'x' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 1.2 },
        { date: '2024-11-14', value: 1.3 },
        { date: '2024-12-14', value: 1.4 },
        { date: '2025-01-06', value: 1.5 }
      ]
    },
    {
      id: 'cost',
      name: 'Financial Index',
      description: 'Financial cost metrics',
      currentValue: 56.0,
      targetValue: 68.0,
      scale: { min: 0, max: 100, unit: '%' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 52.0 },
        { date: '2024-11-14', value: 54.0 },
        { date: '2024-12-14', value: 55.0 },
        { date: '2025-01-06', value: 56.0 }
      ]
    }
  ],
  
  // Learning & Development Department
  'dept-3-1-2': [
    {
      id: 'adoption-percentage',
      name: 'Adoption Percentage',
      description: 'Overall AI adoption rate',
      currentValue: 35.0,
      targetValue: 50.0,
      scale: { min: 1, max: 100, unit: '%' },
      trend: 'up',
      category: 'Adoption',
      history: [
        { date: '2024-10-14', value: 25.0 },
        { date: '2024-11-14', value: 30.0 },
        { date: '2024-12-14', value: 33.0 },
        { date: '2025-01-06', value: 35.0 }
      ]
    },
    {
      id: 'roi',
      name: 'Velocity and Quality',
      description: 'Velocity and Quality metrics',
      currentValue: 1.2,
      targetValue: 2.5,
      scale: { min: 0, max: 10, unit: 'x' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 1.0 },
        { date: '2024-11-14', value: 1.1 },
        { date: '2024-12-14', value: 1.15 },
        { date: '2025-01-06', value: 1.2 }
      ]
    },
    {
      id: 'cost',
      name: 'Financial Index',
      description: 'Financial cost metrics',
      currentValue: 54.0,
      targetValue: 66.0,
      scale: { min: 0, max: 100, unit: '%' },
      trend: 'up',
      category: 'Financial',
      history: [
        { date: '2024-10-14', value: 50.0 },
        { date: '2024-11-14', value: 52.0 },
        { date: '2024-12-14', value: 53.0 },
        { date: '2025-01-06', value: 54.0 }
      ]
    }
  ]
};

/**
 * Recursively collects all child node IDs from an organization node
 */
export function getAllChildNodeIds(node: OrganizationNode): string[] {
  const ids: string[] = [node.id];
  if (node.children && node.children.length > 0) {
    node.children.forEach(child => {
      ids.push(...getAllChildNodeIds(child));
    });
  }
  return ids;
}

/**
 * Gets all leaf node IDs (nodes with no children) from an organization node
 */
export function getLeafNodeIds(node: OrganizationNode): string[] {
  if (!node.children || node.children.length === 0) {
    return [node.id];
  }
  const leafIds: string[] = [];
  node.children.forEach(child => {
    leafIds.push(...getLeafNodeIds(child));
  });
  return leafIds;
}
